### ISSUE TITLE
建议: 增加gf gen dao 增加 --ignore-tables 参数 

### ISSUE THREAD

**Issue by soonio** [gogf/gf-cli#100]
## 使用场景

   在日常使用过程中，经常会增加新的数据表，然后每增加一个表，都要修改一下config.toml中`gfcli.gen.dao`，增加新的数据表。最后导致原来的配置项中的gfcli.gen.dao.tables越来越长。
  有时还因为忘记了在gfcli.gen.dao.tables中追加新的表名，导致gf gen dao时，不生成新增加数据表的dao文件。

## 所以如题，提出建议，通过`--ignore-tables` 控制不生成某些数据表的dao及model

**Comment by gqcn** [comment]
@soonio 正好上个月就已经增加了这个功能。
