### ISSUE TITLE
升级到1.16版本后，生成代码的Dao查询，返回gdb.Record类型

### ISSUE THREAD

**Issue by Pingze-github** [gogf/gf-cli#105]
我从1.15 升级到 1.16后，生成的代码主要变了两点：
1. 取消了internal/model。model直接放在外层了。
2. internal/dao中，不再对所有查询方法做二次封装。查询返回gdb.Record而非具体结构体类型。

这俩更改是什么目的呢？

现在我还要对返回的gdb.Record做Struct()处理

**Comment by LLLjjjjjj** [comment]
+1

**Comment by lepoch** [comment]
+1

**Comment by gqcn** [comment]
@Pingze-github 会在新版发布中介绍，文档还在补齐中。
