### ISSUE TITLE
mac 使用 gf run main.go 寻找路径出错

### ISSUE THREAD

**Issue by zhouyaozhouyao** [gogf/gf-cli#13]
![image](https://user-images.githubusercontent.com/14868140/71650076-a492bb00-2d4e-11ea-8066-28872f654b80.png)
![image](https://user-images.githubusercontent.com/14868140/71650080-ae1c2300-2d4e-11ea-9669-907b627679e9.png)

**Comment by johngcn** [comment]
@zhouyaozhouyao 感谢反馈，请下载最新预编译的工具文件再试试。

**Comment by zhouyaozhouyao** [comment]
大佬厉害，更新修复好了
