### ISSUE TITLE
编译二进制文件端口能指定不

### ISSUE THREAD

**Issue by zhouyaozhouyao** [gogf/gf-cli#17]
![image](https://user-images.githubusercontent.com/14868140/72032964-e0d49700-32cb-11ea-81f3-8f67f31cb427.png)
![image](https://user-images.githubusercontent.com/14868140/72032982-e7fba500-32cb-11ea-950e-b8dbc3ca139f.png)
![image](https://user-images.githubusercontent.com/14868140/72033024-019cec80-32cc-11ea-92bb-10cad9e0d1b2.png)

**Comment by gqcn** [comment]
@zhouyaozhouyao 那个端口是在`server`运行时读取配置文件决定的，因此你在运行的时候保证`config.toml`在你的当前运行目录或者二进制所在目录。具体请参考配置管理章节。
