### ISSUE TITLE
执行./gf install后安装不成功，出现killed:9

### ISSUE THREAD

**Issue by arieslee** [gogf/gf-cli#2]
操作系统mac mojave 10.14.4 (18E226)
go版本1.13
没有任何其他提示
![image](https://user-images.githubusercontent.com/2550216/64582101-21281500-d3bf-11e9-903d-bac1c54d2db7.png)

**Comment by johngcn** [comment]
@arieslee `install`命令是安装`gf`工具到系统目录，我看你那个目录下其实就已经安装成功了。
