### ISSUE TITLE
gf-cli编译失败

### ISSUE THREAD

**Issue by gamegg** [gogf/gf-cli#21]
gf-cli编译失败  

![1111](https://user-images.githubusercontent.com/47522050/73595271-acae6800-4551-11ea-9534-7e65fced545b.png)

**Comment by gamegg** [comment]
`
G:\test\go\gogf\gf-cli>go build main.go
# github.com/gogf/gf-swagger/swagger
D:\Go\cache\pkg\mod\github.com\gogf\gf-swagger@v1.0.2\swagger\swagger.go:76:5: s.Logger undefined (type *ghttp.Server has no field or method Logger)


`

**Comment by duolabmeng6** [comment]
# github.com/gogf/gf-swagger/swagger
..\..\..\..\pkg\mod\github.com\gogf\gf-swagger@v1.0.2\swagger\swagger.go:76:5: s.Logger undefined (type *ghttp.Server has no field or method Logger)
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%

**Comment by ledao** [comment]
遇到相同问题

**Comment by AiPacino** [comment]
遇到相同问题

**Comment by gqcn** [comment]
@gamegg @duolabmeng6 @ledao @AiPacino 试试最新版本。
