### ISSUE TITLE
swagger 无法生成swagger.json

### ISSUE THREAD

**Issue by lwk5213** [gogf/gf-cli#22]
gf run main.go --swagger -mod=vendor
2020-02-16 19:24:33.577 build: main.go
2020-02-16 19:24:33.640 producing swagger files...
2020-02-16 19:24:33.779 Incorrect Usage: flag provided but not defined: -o

NAME:
   swag init - Create docs.go

USAGE:
   swag init [command options] [arguments...]

OPTIONS:
   --generalInfo value       Go file path in which 'swagger general API Info' is written (default: "main.go")
   --dir value               Directory you want to parse (default: "./")
   --propertyStrategy value  Property Naming Strategy like snakecase,camelcase,pascalcase (default: "camelcase")          --output value            Output directory for all the generated files(swagger.json, swagger.yaml and doc.go) (default: "./docs")
   --parseVendor             Parse go files in 'vendor' folder, disabled by default (default: false)
   --parseDependency         Parse go files in outside dependency folder, disabled by default (default: false)
   --markdownFiles value     Parse folder containing markdown files to use as description, disabled by default
   --generatedTime           Generate timestamp at the top of docs.go, true by default (default: false)
   --help, -h                show help (default: false)

2020/02/16 19:24:33 flag provided but not defined: -o

**Comment by lwk5213** [comment]
swag -h
NAME:
   swag - Automatically generate RESTful API documentation with Swagger 2.0 for Go.

USAGE:
   swag [global options] command [command options] [arguments...]

VERSION:
   v1.6.5

COMMANDS:
   init, i  Create docs.go
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help (default: false)
   --version, -v  print the version (default: false)

**Comment by lwk5213** [comment]
gf -v
GoFrame CLI Tool v0.6.0, https://goframe.org
Install Path: C:\Users\Ke\go\bin\gf.exe
Build Detail:
  Go Version:  go1.13.5
  GF Version:  v1.11.3
  Git Commit:  2079c3b19349f6dc3890c210e32503dd7d04dbeb
  Build Time:  2020-01-18 00:12:13

**Comment by AiPacino** [comment]
+1

**Comment by gqcn** [comment]
@lwk5213 @AiPacino 试试最新版本。
