### ISSUE TITLE
cli的gen命令下config选项处理条件逻辑有问题

### ISSUE THREAD

**Issue by veincheng** [gogf/gf-cli#26]
gen 命令处理config选项中 代码逻辑错误
函数doGenModel处理config值中一个if 条件中 `setFileName` 中报错
看其源码是返回正常对象，代码却是按捕获error的思路去处理。
![捕获](https://user-images.githubusercontent.com/503212/76521581-10f10f80-64a0-11ea-89f3-c8557872faa3.PNG)

**Comment by gqcn** [comment]
@veincheng 感谢反馈，新版本已解决。
