### ISSUE TITLE
gf gen model 命令中的表前缀是否能自动读取配置文件中的表前缀？

### ISSUE THREAD

**Issue by gutink** [gogf/gf-cli#29]
配置文件中已经设置好表前缀参数(prefix = “app_”)，但执行 gf gen model 命令时，生成的文件依旧带有表前缀(如"app\model\app_users\app_users_entity.go")，需要执行 gf gen model -p "app_" 生成出来的文件才会去掉表前缀。

**Comment by gqcn** [comment]
@gutink 两者用途不一样哦，用命令行吧。
