### ISSUE TITLE
希望可以自定义gen命令要生成的表名和模型名,虽然全部生成了再改也不算复杂

### ISSUE THREAD

**Issue by sth4me** [gogf/gf-cli#3]
如题。在传了表名和模型名的时候，自动忽略生成全部表的效果，例如gf -t tableName -m modelName 生成的是对应数据库表tableName，文件名为modelName.go的模型文件。
最好有强制覆盖的选项，例如-f。

全部生成再copy或者move到实际项目目录中修改其实也不复杂，就是相对不方便。

**Comment by johngcn** [comment]
@sth4me 已增加`-t`参数用以指定需要生成的表名。
