### ISSUE TITLE
增加upx压缩选项

### ISSUE THREAD

**Issue by fxk2006** [gogf/gf-cli#41]
郭大神，这个cli工具好用，希望增加一个upx压缩选项，例如，配置了upx.exe的路径时，自动调用upx压缩

**Comment by botsphp** [comment]
自己写个 make 脚本他不香吗

**Comment by gqcn** [comment]
@fxk2006 自己写个Makefile吧。

**Comment by gqcn** [comment]
@fxk2006 自己写个Makefile吧。
