### ISSUE TITLE
MacOS系统 gf-cli 错误

### ISSUE THREAD

**Issue by 0ytian** [gogf/gf-cli#5]
我是macos系统，我按照 gf install 之后，gf 被安装到了/usr/local/bin/gf，我直接使用/usr/local/bin/gf命令正常，但是直接输入gf 命令的时候报错：
`fatal: not a git repository (or any of the parent directories): .git`

**Comment by LanceAdd** [comment]
@0ytian 你可能使用了zsh的git插件，zsh的git插件把git fetch给alias成gf了，和gf-cli的gf冲突了，你可以
```
 alias gf="~/gf"

**Comment by johngcn** [comment]
@0ytian @LanceAdd 使用` alias gf="gf"`解决。

**Comment by gqcn** [comment]
@0ytian 新版本的`gf`工具会自动修改`zsh`的配置，增加自动的别名覆盖，新建`shell tab`后即可生效。
