### ISSUE TITLE
Mac下安装gf-cli失败， zsh: exec format error: ./gf

### ISSUE THREAD

**Issue by yqbboy** [gogf/gf-cli#53]
renxuedong@yq  ~  wget https://goframe.org/cli/linux_amd64/gf && chmod +x gf && ./gf install
--2020-08-19 19:00:12--  https://goframe.org/cli/linux_amd64/gf
正在解析主机 goframe.org (goframe.org)... 47.244.3.49
正在连接 goframe.org (goframe.org)|47.244.3.49|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Found
位置：https://gfcdn.johng.cn/cli/linux_amd64/gf?534618d654b6f921ff166a0ccdc2f94f [跟随至新的 URL]
--2020-08-19 19:00:14--  https://gfcdn.johng.cn/cli/linux_amd64/gf?534618d654b6f921ff166a0ccdc2f94f
正在解析主机 gfcdn.johng.cn (gfcdn.johng.cn)... 36.99.196.217
正在连接 gfcdn.johng.cn (gfcdn.johng.cn)|36.99.196.217|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：21877703 (21M) [application/octet-stream]
正在保存至: “gf”

gf                                              100%[=====================================================================================================>]  20.86M  1.37MB/s  用时 16s

2020-08-19 19:00:31 (1.31 MB/s) - 已保存 “gf” [21877703/21877703])

zsh: exec format error: ./gf

**Comment by php2go** [comment]
同上，我这边也是这个错误不知道什么原因

**Comment by php2go** [comment]
你这个是下载包下错了应该下：https://goframe.org/cli/darwin_amd64 下载完了拷贝到  sudo cp gf /usr/local/bin 就ok
