### ISSUE TITLE
生成model代码增强

### ISSUE THREAD

**Issue by fxk2006** [gogf/gf-cli#6]
1、设置忽略表的前缀，列如习惯表开头用“t_”, 如t_user,   t_file;
      习惯函数开头用"f_",  存储过程开头“pr_”
      但生成model需要忽略掉前缀
2、生成model希望能把表字段注释和表注释带过来，方便阅读代码

thanks,John

**Comment by gqcn** [comment]
@fxk2006 新版本的`gf gen model`命令增加了`-p`参数，请更新版本再试试。
![image](https://user-images.githubusercontent.com/26347176/72627005-b26b5180-3986-11ea-851f-86eaa637c278.png)
