### ISSUE TITLE
MSSQL 使用gf gen model命令生成的实体错误

### ISSUE THREAD

**Issue by yuliang2417535997** [gogf/gf-cli#60]
生成的_entity 和_model 文件缺少字段信息
![image](https://user-images.githubusercontent.com/26182238/96006503-241df080-0e70-11eb-8c40-7724e4bcfc42.png)

![image](https://user-images.githubusercontent.com/26182238/96007356-fdac8500-0e70-11eb-98a0-beb1c4684439.png)

**Comment by gqcn** [comment]
@yuliang2417535997 请使用最新的`cli`版本试试，通过`gf update`升级即可。

**Comment by prcseraph** [comment]
gf update后，还是一样的结果，我也遇到了此情况了。

**Comment by gqcn** [comment]
@prcseraph @yuliang2417535997 之前这里有个BUG，后面是修复了的，你们可以在微信 389961817 上联系下我，我帮你们看看？

**Comment by prcseraph** [comment]
@gqcn 找到问题，database/gdb/gdb_driver_mssql.go第214行Field改成全大写就解决了。

**Comment by gqcn** [comment]
@prcseraph 这里之前有BUG，我统一改称了驼峰的。
