### ISSUE TITLE
域名路由使用方法请教

### ISSUE THREAD

**Issue by mygithub-hang** [gogf/gf-cli#61]
作者大大您好，我是一位PHP开发者主要使用thinkphp，目前转向go语言使用gf框架开发
自我感觉，gf框架对PHP开发者非常友好，通俗易懂。
**目前遇到有一个需求，才疏学浅难以实现，希望作者大大不吝赐教**
需求：根据不同的域名前缀访问不同的模块
**详情：在域名泛解析的前提下**

1. admin.domain.com 访问 后台
2. wap.domain.com 访问移动端
3. api.domain.com 访问api接口
4. 除了admin,wap,api外的域名前缀包括无前缀都访问 wwwPC端

目前根据文档提供的域名路由实现了前面三个域名与对应的路由绑定
最后一个无法实现

谢谢作者大大，作者大大辛苦了

**Comment by liserven** [comment]
这种是nginx做的处理吧

**Comment by gqcn** [comment]
@mygithub-hang `gf Server`对域名的支持比较简单，域名这块可以有但是不需要做得精，并且也不是它专注需要去完善的事情。建议你可以考虑前置Nginx或者通过中间件、钩子方法自己在代码内部对`r.Host`做判断。

**Comment by mygithub-hang** [comment]
> @ mygithub-hang `gf Server`对域名的支持比较简单，域名这块可以有但是不需要做得精，并且也不是它专注需要去完善的事情。建议您可以考虑使用Nginx或者通过中间件，钩子方法自己在代码内部对`r.Host`做判断。

好的，谢谢大大
