### ISSUE TITLE
windows gf init 生成一个新项目，gf run main报错

### ISSUE THREAD

**Issue by liserven** [gogf/gf-cli#62]
使用init命令生成一个新的项目

使用gf run main.go报错

![image](https://user-images.githubusercontent.com/34682164/97149365-a0390200-17a7-11eb-9890-ae3905c96753.png)

**Comment by gqcn** [comment]
@liserven 使用的是最新的`gf-cli`么？尝试使用`gf run main.go`试试？

**Comment by liserven** [comment]
> @liserven 使用的是最新的`gf-cli`么？尝试使用`gf run main.go`试试？

这样可以

**Comment by gqcn** [comment]
@liserven 可能是目录解析没处理好，我标记一下，不着急处理，能有小伙伴提供PR就好了。
