### ISSUE TITLE
gf run 可以指定-o吗

### ISSUE THREAD

**Issue by lepoch** [gogf/gf-cli#66]

**Comment by gqcn** [comment]
@lepoch 不可以

**Comment by lepoch** [comment]
我这边准备多个项目同时运行http.go，会有冲突，有计划支持一下吗？

也可以直接用 `tempDir = os.TempDir()`

**Comment by gqcn** [comment]
> 我这边准备多个项目同时运行http.go，会有冲突，有计划支持一下吗？
> 
> 也可以直接用 `tempDir = os.TempDir()`

好的。。那可以。

**Comment by gqcn** [comment]
@lepoch 通过将自动编译的二进制文件路径改为到当前项目目录的`./bin`目录来解决冲突，请执行`gf update`再试试。

**Comment by lepoch** [comment]
手动点赞
