### ISSUE TITLE
cannot find the dao Ctx function

### ISSUE THREAD

**Issue by keminshu** [gogf/gf-cli#68]
when i use `gf gen dao -r weixin_`, it generate a dao function in the dao/internal/xxx.go, but it lacks of the Ctx function.
As the follow msg show,
![image](https://user-images.githubusercontent.com/10050045/102691598-992eed00-4248-11eb-97f3-3c33a7b82a0f.png)
gf frame version:v1.14.5
gf-cli version:v1.14.5

**Comment by gqcn** [comment]
@keminshu Please use the latest `gf` version.
