### ISSUE TITLE
gf gen model -p 不生效

### ISSUE THREAD

**Issue by lepoch** [gogf/gf-cli#72]
如题，生成 model 时，没法加前缀。
我这一个工程可能涉及到多个数据库，现在时生成之后再去修改每个包的前缀。
这种方式会造成没法直接更新 _model.go，比如最近的 ctx 方法。
有计划支持该功能吗？

**Comment by gqcn** [comment]
@lepoch 你好，`gen model`不支持`gen dao`是支持加前缀的，未来都不推荐使用`gen model`的方式了，你可以研究一下`gen dao`：https://itician.org/pages/viewpage.action?pageId=1115790
