### ISSUE TITLE
gf 最新版本v1.15.3，gen dao 疑问...

### ISSUE THREAD

**Issue by zhangxa** [gogf/gf-cli#84]
gen_dao_template_dao.go 文件，{TplTableNameCamelCase}Dao是不是应为& 指针结构体，少了&。
还是使用方法变了？
当前代码如下：
> // {TplTableNameCamelCase} is globally public accessible object for table {TplTableName} operations.
	{TplTableNameCamelCase} = {TplTableNameCamelCase}Dao{
		M:     g.DB("{TplGroupName}").Model("{TplTableName}").Safe(),
		DB:    g.DB("{TplGroupName}"),
		Table: "{TplTableName}",
		Columns: {TplTableNameCamelLowerCase}Columns{
			{TplColumnNames}
		},
	}

**Comment by gqcn** [comment]
@zhangxa 你好，是的，这块新版本有变化，具体请参考设计文档中的 对象访问安全 章节：https://goframe.org/pages/viewpage.action?pageId=3672526
