### ISSUE TITLE
gen生成模型结构体能否去掉表前缀

### ISSUE THREAD

**Issue by lnz0212** [gogf/gf-cli#9]
gen生成模型结构体能否去掉表前缀
![image](https://user-images.githubusercontent.com/3981218/70313461-a56c2600-1850-11ea-9309-8df38c91f64f.png)

**Comment by gqcn** [comment]
@lnz0212 新版本的`gf gen model`命令增加了`-p`参数，请更新版本再试试。
![image](https://user-images.githubusercontent.com/26347176/72627005-b26b5180-3986-11ea-851f-86eaa637c278.png)
