### ISSUE TITLE
M1版本MAC安装提示no path detected

### ISSUE THREAD

**Issue by BlankRan** [gogf/gf-cli#90]
原因可能是M1版本的MAC电脑没有权限在 /usr/local/bin 的目录下创建文件 sudo也没权限，导致提示no path detected, you can manually install gf by copying the binary to path folder.
不知道是不是只有我一个人遇到这个问题
通过代码找到了路径地址，修改了路径地址问题解决
![image](https://user-images.githubusercontent.com/49958122/111614136-3682c880-881a-11eb-893d-c2228bb55b69.png)

**Comment by winlily** [comment]
关闭SIP即可，操作步骤：
1，关机
2，长按电源键，进入到恢复模式
3，选择终端，查看状态
csrutil status，如果是 enable 即为开启状态
4，执行 csrutil disable 关闭SIP
5，重启电脑

**Comment by eva00rei00** [comment]
@winlily m1关csrutil没用了,还是没权限,需要很麻烦的操作才行

**Comment by wangbs95** [comment]
> 原因可能是M1版本的MAC电脑没有权限在 /usr/local/bin 的目录下创建文件 sudo也没权限，导致提示no path detected, you can manually install gf by copying the binary to path folder.
> 不知道是不是只有我一个人遇到这个问题
> 通过代码找到了路径地址，修改了路径地址问题解决
> ![image](https://user-images.githubusercontent.com/49958122/111614136-3682c880-881a-11eb-893d-c2228bb55b69.png)

完美解决，不过我是按在 $gopath/bin 下面的

**Comment by tcxiaotudou** [comment]
官方啥时候能支持一下M1版本的呢？
